<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * File Details Template for the OntoWiki Files Extension Module
 *
 * @category OntoWiki
 * @package  OntoWiki_extensions_files
 * @author   {@link http://sebastian.tramp.name Sebastian Tramp}
 */
?>
<p class="message info">
    <?php echo $this->_('There is an attached file document on this resource') ?>
</p>
