<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * Upload Template for the OntoWiki Files Extension Module
 *
 * @category OntoWiki
 * @package  OntoWiki_extensions_files
 * @author   {@link http://sebastian.tramp.name Sebastian Tramp}
 */

$url  = new OntoWiki_Url(
    array(
        'controller' => 'files',
        'action' => 'upload'
    ),
    array()
);
?>
<div class="messagebox info has-contextmenu-area">
    <?php echo $this->_('Currently, no file is attached to this resource.') ?>
    <div class="contextmenu">
        <a
            href="<?php echo $url . '?setResource=' . urlencode($this->file_uri) ?>"
            class="item">
            <span class="icon icon-add" title="<?php echo $this->_('Upload File') ?>">
                <span><?php echo $this->_('Upload File') ?></span>
            </span>
        </a>
    </div>
</div>
