<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * File Details Template for the OntoWiki Files Extension Module
 *
 * @category OntoWiki
 * @package  OntoWiki_extensions_files
 * @author   {@link http://sebastian.tramp.name Sebastian Tramp}
 */

$deleteUrl  = new OntoWiki_Url(
    array(
        'controller' => 'files',
        'action' => 'delete'
    ),
    array()
);
$deleteUrl = (string) $deleteUrl . '?setResource='.$this->file_uri;

$getUrl  = new OntoWiki_Url(
    array(
        'controller' => 'files',
        'action' => 'get'
    ),
    array()
);
$getUrl = (string) $getUrl . '?setResource='.$this->file_uri;

$mimeType = $this->mimeType;
?>
<div class="messagebox info has-contextmenu-area">
    <p><?php echo $this->_('There is an attached file document on this resource') ?></p>
    <p>
        The attached file is of type <code><?php echo $mimeType?></code> and you can
        <a href="<?php echo $getUrl ?>">download it</a>.
    </p>
    <div class="contextmenu">
        <a
            href="<?php echo $getUrl ?>"
            class="item">
            <span class="icon icon-save" title="<?php echo $this->_('Download Attachment') ?>">
                <span><?php echo $this->_('Download Attachment') ?></span>
            </span>
        </a>
        <a
            href="<?php echo $deleteUrl ?>"
            class="item">
            <span class="icon icon-delete" title="<?php echo $this->_('Delete Attachment') ?>">
                <span><?php echo $this->_('Delete Attachment') ?></span>
            </span>
        </a>
    </div>
</div>
