<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * Upload Template for the OntoWiki Files Extension
 *
 * @category OntoWiki
 * @package  OntoWiki_extensions_files
 * @author   Christoph Rieß
 * @author   Norman Heino <norman.heino@gmail.com>
 * @author   Sebastian Tramp <mail@sebastian.tramp.name>
 */

if (isset($this->setResource)) {
    $fileUri      = $this->setResource;
    $readOnlyFlag = 'readonly';
    // this hidden value is used for redirecting
    $hiddenInput = '<input type="hidden" name="setResource" value="'.$this->setResource.'" />';
} else {
    $fileUri      = $this->defaultUri;
    $readOnlyFlag = '';
    $hiddenInput  = '';
}
?>
<fieldset id="upload" class="form">
    <legend></legend>
    <div>
        <?php echo $hiddenInput ?>
        <label for="file_uri"><?php echo $this->_('Resource URI') ?></label>
        <input
            class="text prefix-value"
            value="<?php echo $fileUri ?>"
            type="text"
            name="file_uri"
            id="file_uri"
            size="10"
            <?php echo $readOnlyFlag ?>
        />
    </div>
    <div>
        <label for="file-input">
            <?php echo sprintf($this->_('File (max. %1$sB)'), preg_replace('/([kMG])/', ' $1', ini_get('upload_max_filesize'))) ?>
        </label>
        <input type="file" id="file-input" name="upload" />
        <br class="clearall" />
    </div>
</fieldset>
